title = skyblock_void
description = 虚空觉醒空岛子游戏
game_version = 0.1
min_minetest_version = 5.0
allowed_mapgens = singlenode
disallowed_mapgens = v5,v6,v7,carpatian,valleys,flat,fractal
default_mapgen = singlenode
